"""add cascade delete to messages

Revision ID: 6c28b2a6b871
Revises: dbb539042d94
Create Date: 2026-04-05 17:50:29.443613

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6c28b2a6b871'
down_revision: Union[str, Sequence[str], None] = 'dbb539042d94'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('messages_document_id_fkey'), 'messages', type_='foreignkey')
    op.create_foreign_key(None, 'messages', 'documents', ['document_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.create_foreign_key(op.f('messages_document_id_fkey'), 'messages', 'documents', ['document_id'], ['id'])
    # ### end Alembic commands ###
