"""add s3_key to documents

Revision ID: dbb539042d94
Revises: 7e92ce6d2d3b
Create Date: 2026-03-25 16:08:24.146035

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dbb539042d94'
down_revision: Union[str, Sequence[str], None] = '7e92ce6d2d3b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('s3_key', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 's3_key')
    # ### end Alembic commands ###
